### PR TITLE
Convert DAB RBAC to using its own concrete permission model

### PR DESCRIPTION
**Pull request by AlanCoding**

### CODE REVIEW

**Review by Dostonbek1 — APPROVED** [review]
This looks good to me. I would really like to test it on EDA, speaking of which we should put up a follow-up PR on eda-server to fetch these changes.

**Comment by AlanCoding** [comment]
Good point, this needs a followup PR in both eda-server and AWX. The sticking point there is the migration dependencies. They both have steps inserted into their migrations to create permissions before migrating roles. They could both add a RunPython to call the post_migrate method here.

Or... alternatively, it might be best if DAB RBAC inserts a step in its own 0001 migration to create permissions. This would be _in addition to_ the post-migrate signal. This would allow the apps to get rid of the "sandwich" migrations they have.

**Comment by AlanCoding** [comment]
> Or... alternatively, it might be best if DAB RBAC inserts a step in its own 0001 migration to create permissions.

Nope nope nope nope.

DAB RBAC doesn't control the dependencies going in the other direction. So it is _likely_ that the DAB migrations fully finish before the other apps do. The permission registry is filled out, but none of those other models exist in the database. This wouldn't be a problem except for the ContentType dependency... and that no content types will exist, because the models don't exist. So not possible.

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/compare/feature_dab_rbac...AlanCoding:no_permission?expand=1

**Comment by AlanCoding** [comment]
https://github.com/ansible/eda-server/pull/738

also required to happen at the same time as this.

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/pull/14994

**Pull request merged**
